package com.dpay.common.events;

public enum GatewayEventType {
    PAYMENT_CREATED,
    PAYMENT_CONFIRM_REQUESTED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_CANCELED,
    REFUND_REQUESTED,
    REFUND_SUCCEEDED,
    REFUND_FAILED,
    TRANSFER_REQUESTED,
    TRANSFER_FUNDS_RESERVED,
    TRANSFER_CREDITING,
    TRANSFER_COMPLETED,
    TRANSFER_COMPENSATING,
    TRANSFER_COMPENSATED,
    TRANSFER_FAILED
}
